"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Script from "next/script";
import SideNavbar from "@/components/SideNavbar";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Candidate Hub",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Script src="/tinymce/tinymce.min.js" />
        <Navbar />
        <div className="flex gap-4 px-36 container">
          <div
            className={`mt-24  ${
              pathname.includes("/auth") ? "hidden" : "block"
            }`}
          >
            <SideNavbar />
          </div>

          <div className="w-[1000px] max-w-[1000px] min-w-[1000px] my-24 bg-white">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
